image: ruby:2.3

variables:
  JEKYLL_ENV: production

pages:
  script:
  - gem install jekyll bundler
  - bundle install
  - bundle exec jekyll build -d public
  artifacts:
    paths:
    - public
  only:
  - master