permalink: pretty

collections:
  projects:
    output: true
  cambodia_project:
    output: true
    permalink: /cambodia/project/:name
  cambodia_journal:
    output: true
    permalink: /cambodia/journal/:name
  eswatini_journal:
    output: true
    permalink: /eswatini/journal/:name

defaults:
  - scope:
      path: ""
      type: "cambodia_project"
    values:
      layout: "project"
  - scope:
      path: "/cambodia/project/*"
    values:
      layout: "project"
  - scope:
      path: "/eswatini/project/*"
    values:
      layout: "project"
  - scope:
      path: "/cambodia/journal/*"
    values:
      layout: "red_block"
  - scope:
      path: "/eswatini/journal/*"
    values:
      layout: "red_block"
  - scope:
      path: ""
      type: "cambodia_journal"
    values:
      layout: "journal"
  - scope:
      path: ""
      type: "eswatini_journal"
    values:
      layout: "journal"
  - scope:
      path: ""
    values:
      layout: "default"